name: taskdoni

services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_DATABASE=taskdoni'
      - 'MYSQL_USER=main_user'
      - 'MYSQL_PASSWORD=secret'
    networks:
      - main
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8090:80
    environment:
      - 'PMA_HOST=mysql'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
    networks:
      - main

networks:
  main:

volumes:
  db_data: